server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service  # Eureka lookup
          predicates:
            - Path=/api/users/**
      resilience4j:
        circuitbreaker:
          instances:
            user-service:
              sliding-window-size: 10
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka