server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: truedocker-compose logs config-server
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: user-events
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka