spring:
  application:
    name: notification-service
  profiles:
    active: docker
  config:
    import: optional:configserver:http://config-server:8888
    allow-override: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.model.*
      topic: user-events
    listener:
      concurrency: 1
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    eureka-server-read-timeout-seconds: 20
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
    eureka:
      enabled: true
    mail:
      enabled: false
logging:
  level:
    root: INFO
    com.netflix.eureka: DEBUG
    org.springframework.kafka: INFO
    com.example: INFO