server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      topic: user-events
  cloud:
    config:# Для environment overrides
profiles:
  active: docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    eureka-server-connect-timeout-seconds: 20
    eureka-server-read-timeout-seconds: 20
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics