spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %X{requestId} %logger{36} - %msg%n
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN


spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true



spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.retries=0
spring.kafka.producer.acks=0
spring.kafka.producer.properties.max.block.ms=1000
spring.kafka.producer.properties.delivery.timeout.ms=1500


spring.kafka.producer.properties.request.timeout.ms=1000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.properties.allow.auto.create.topics=true


