server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.config.server.environment.NativeEnvironmentRepository: DEBUG