server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud: INFO